spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
        url: jdbc:mysql://localhost:3306/library?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B9&rewriteBatchedStatements=true
        username: root
        password: Jiangwen@99
        type: com.alibaba.druid.pool.DruidDataSource   #使用druid数据源
        driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    protocol: smtp
    username: 303551686@qq.com
    password: xxx
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: jp.ips.admin.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句

mail:
  fromMail:
    address: 303551686@qq.com
